//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beltelekom.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Contract { get; set; }
        public string FIOClient { get; set; }
        public string Phone { get; set; }
        public string FIOPerformer { get; set; }
        public string Address { get; set; }
        public int ServiceId { get; set; }
        public double Sum { get; set; }
    }
}
